/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
Source:  https://www.youtube.com/watch?v=XAowXcmQ-kA&t=1074s
//suivi du turtoriel 
//interface faite en utilisant les outils "Design" de Netbeans
 */
package View;

import Controller.MyController;

/**
 *
 * @author mahtt
 */
public class Accueil extends javax.swing.JFrame {

    MyController m_controler;

    /**
     * Creates new form Accueille
     */
    public Accueil(MyController c) {
        initComponents();
        this.setLocationRelativeTo(null);
        m_controler = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ButtonInterfaceClient = new javax.swing.JButton();
        BoutonInterfaceEmploye = new javax.swing.JButton();
        BoutonInterfaceCinema = new javax.swing.JButton();
        LeBoutonAsupprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(108, 122, 137));

        jPanel4.setBackground(new java.awt.Color(3, 138, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Accueil");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        ButtonInterfaceClient.setBackground(new java.awt.Color(52, 45, 113));
        ButtonInterfaceClient.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ButtonInterfaceClient.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInterfaceClient.setText("Client");
        ButtonInterfaceClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInterfaceClientActionPerformed(evt);
            }
        });

        BoutonInterfaceEmploye.setBackground(new java.awt.Color(52, 45, 113));
        BoutonInterfaceEmploye.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        BoutonInterfaceEmploye.setForeground(new java.awt.Color(255, 255, 255));
        BoutonInterfaceEmploye.setText("Employé");
        BoutonInterfaceEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonInterfaceEmployeActionPerformed(evt);
            }
        });

        BoutonInterfaceCinema.setBackground(new java.awt.Color(52, 45, 113));
        BoutonInterfaceCinema.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        BoutonInterfaceCinema.setForeground(new java.awt.Color(255, 255, 255));
        BoutonInterfaceCinema.setText("Cinéma");
        BoutonInterfaceCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonInterfaceCinemaActionPerformed(evt);
            }
        });

        LeBoutonAsupprimer.setText("Le bouton de Cyriac et Alix");
        LeBoutonAsupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeBoutonAsupprimerMouseClicked(evt);
            }
        });
        LeBoutonAsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeBoutonAsupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BoutonInterfaceCinema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BoutonInterfaceEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(ButtonInterfaceClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(186, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LeBoutonAsupprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(ButtonInterfaceClient)
                .addGap(18, 18, 18)
                .addComponent(BoutonInterfaceEmploye)
                .addGap(26, 26, 26)
                .addComponent(BoutonInterfaceCinema)
                .addGap(18, 18, 18)
                .addComponent(LeBoutonAsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonInterfaceClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInterfaceClientActionPerformed
        // TODO add your handling code here:
        this.dispose();
        m_controler.AfficheInterfaceClient(m_controler);
    }//GEN-LAST:event_ButtonInterfaceClientActionPerformed

    private void BoutonInterfaceEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonInterfaceEmployeActionPerformed
        // TODO add your handling code here:

        this.dispose();
        m_controler.AfficheInterfaceEmploye(m_controler);
    }//GEN-LAST:event_BoutonInterfaceEmployeActionPerformed

    private void BoutonInterfaceCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonInterfaceCinemaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        m_controler.AfficheInterfaceFilm(m_controler);
    }//GEN-LAST:event_BoutonInterfaceCinemaActionPerformed

    private void LeBoutonAsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeBoutonAsupprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeBoutonAsupprimerActionPerformed

    private void LeBoutonAsupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeBoutonAsupprimerMouseClicked
        // TODO add your handling code here:
        this.dispose();
        m_controler.AfficheInterfaceModifEmployé(m_controler);
    }//GEN-LAST:event_LeBoutonAsupprimerMouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil(m_controler).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonInterfaceCinema;
    private javax.swing.JButton BoutonInterfaceEmploye;
    private javax.swing.JButton ButtonInterfaceClient;
    private javax.swing.JButton LeBoutonAsupprimer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
