/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MyController;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import Model.films;

/**
 *
 * @author vdrcy
 */
public class InfoFilm extends javax.swing.JFrame {

    MyController m_controler;
    String m_titre;
    String m_Genre;
    String m_Intrigue;
    String m_Realisateur;
    String m_Acteur;
    int m_id;

    /**
     * Creates new form InfoFilm
     */
    public InfoFilm(MyController c, String Titre, String Genre, String Intrigue, String Realisateur, String Acteur, int id) {
        initComponents();
        m_controler = c;
        m_titre = Titre;
        m_Genre = Genre;
        m_Intrigue = Intrigue;
        m_Realisateur = Realisateur;
        m_Acteur = Acteur;
        m_id = id;
        LabelTitre.setText(Titre);
        LabelGenre.setText(Genre);
        LabelIntrigue.setText(Intrigue);
        LabelRealisateur.setText(Realisateur);
        LabelActeur.setText(Acteur);
        m_controler.ChoisirFilm(id, m_controler, LabelUrl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitre = new javax.swing.JLabel();
        LabelGenre = new javax.swing.JLabel();
        LabelIntrigue = new javax.swing.JLabel();
        LabelRealisateur = new javax.swing.JLabel();
        LabelActeur = new javax.swing.JLabel();
        LabelDate = new javax.swing.JLabel();
        LabelUrl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitre.setText("Titre");

        LabelGenre.setText("Genre");

        LabelIntrigue.setText("Intrigue");

        LabelRealisateur.setText("Realisateur");

        LabelActeur.setText("Acteur");

        LabelDate.setText("Date");

        LabelUrl.setText("Url");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(LabelDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelRealisateur)
                            .addComponent(LabelIntrigue)
                            .addComponent(LabelGenre)
                            .addComponent(LabelActeur)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(LabelUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(LabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(LabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(LabelGenre)
                .addGap(46, 46, 46)
                .addComponent(LabelIntrigue)
                .addGap(43, 43, 43)
                .addComponent(LabelRealisateur)
                .addGap(48, 48, 48)
                .addComponent(LabelActeur)
                .addGap(79, 79, 79)
                .addComponent(LabelDate)
                .addGap(7, 7, 7)
                .addComponent(LabelUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoFilm(m_controler, m_titre, m_Genre,m_Intrigue,m_Realisateur,m_Acteur, m_id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelActeur;
    private javax.swing.JLabel LabelDate;
    private javax.swing.JLabel LabelGenre;
    private javax.swing.JLabel LabelIntrigue;
    private javax.swing.JLabel LabelRealisateur;
    private javax.swing.JLabel LabelTitre;
    private javax.swing.JLabel LabelUrl;
    // End of variables declaration//GEN-END:variables
}
