/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
Source:  https://www.youtube.com/watch?v=XAowXcmQ-kA&t=1074s
//suivi du turtoriel 
//interface faite en utilisant les outils "Design" de Netbeans
 */
package View;

import Controller.MyController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author matth
 */
public class InterfaceInscriptionClient extends javax.swing.JFrame {

    MyController m_controler;
    /**
     * Creates new form InterfaceInscriptionClient
     */

    private String recupAbonnement;
    private String recupMdp;
    private String recupMail;
    private String recupUser;
    private String recupFact;
    private Boolean Connecte;

    public InterfaceInscriptionClient(MyController c) {
        initComponents();
        this.setLocationRelativeTo(null);
        recupAbonnement = "PleinTarif";
        recupMdp = null;
        recupMail = null;
        recupFact = null;
        Boolean Connecte = false;
        m_controler = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        RetourInterfaceClient = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SaisieUser = new javax.swing.JTextField();
        SaisieMdp = new javax.swing.JPasswordField();
        EnregistrerClient = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SaisieMail = new javax.swing.JTextField();
        AbonnementEnfant = new javax.swing.JCheckBox();
        AbonnementRegulier = new javax.swing.JCheckBox();
        AbonnementSenior = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));

        jPanel1.setBackground(new java.awt.Color(3, 138, 255));

        RetourInterfaceClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RetourInterfaceClient.setForeground(new java.awt.Color(255, 255, 255));
        RetourInterfaceClient.setText("Retour");
        RetourInterfaceClient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RetourInterfaceClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetourInterfaceClientMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inscription Client");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(RetourInterfaceClient)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RetourInterfaceClient))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mot de passe :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nom d'utilisateur :");

        SaisieUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SaisieUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaisieUserActionPerformed(evt);
            }
        });

        SaisieMdp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SaisieMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaisieMdpActionPerformed(evt);
            }
        });

        EnregistrerClient.setBackground(new java.awt.Color(30, 130, 76));
        EnregistrerClient.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        EnregistrerClient.setForeground(new java.awt.Color(255, 255, 255));
        EnregistrerClient.setText("Enregistrer");
        EnregistrerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerClientActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adresse e-mail :");

        SaisieMail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SaisieMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaisieMailActionPerformed(evt);
            }
        });

        AbonnementEnfant.setBackground(new java.awt.Color(153, 153, 153));
        AbonnementEnfant.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AbonnementEnfant.setForeground(new java.awt.Color(255, 255, 255));
        AbonnementEnfant.setText("Enfant");
        AbonnementEnfant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbonnementEnfantMouseClicked(evt);
            }
        });

        AbonnementRegulier.setBackground(new java.awt.Color(153, 153, 153));
        AbonnementRegulier.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AbonnementRegulier.setForeground(new java.awt.Color(255, 255, 255));
        AbonnementRegulier.setText("Régulier");
        AbonnementRegulier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbonnementRegulierMouseClicked(evt);
            }
        });

        AbonnementSenior.setBackground(new java.awt.Color(153, 153, 153));
        AbonnementSenior.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AbonnementSenior.setForeground(new java.awt.Color(255, 255, 255));
        AbonnementSenior.setText("Senior");
        AbonnementSenior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbonnementSeniorMouseClicked(evt);
            }
        });
        AbonnementSenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbonnementSeniorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EnregistrerClient)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SaisieMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(SaisieUser)
                            .addComponent(SaisieMail)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AbonnementRegulier, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AbonnementSenior, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(AbonnementEnfant, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SaisieUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(SaisieMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SaisieMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbonnementEnfant, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbonnementSenior, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbonnementRegulier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(EnregistrerClient, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaisieMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaisieMdpActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SaisieMdpActionPerformed

    private void EnregistrerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerClientActionPerformed
        recupMdp = String.valueOf(SaisieMdp.getPassword());
        recupMail = SaisieMail.getText();
        recupUser = SaisieUser.getText();

        try {
            m_controler.inscription(recupUser, recupMail, recupAbonnement, "non", recupMdp, m_controler);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(InterfaceInscriptionClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            m_controler.CookieClient(SaisieMail.getText(), m_controler);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(InterfaceInscriptionClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        this.dispose();

    }//GEN-LAST:event_EnregistrerClientActionPerformed

    private void RetourInterfaceClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetourInterfaceClientMouseClicked
        // TODO add your handling code here:

        this.dispose();
        m_controler.AfficheInterfaceClient(m_controler);
    }//GEN-LAST:event_RetourInterfaceClientMouseClicked

    private void SaisieUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaisieUserActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SaisieUserActionPerformed

    private void SaisieMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaisieMailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SaisieMailActionPerformed

    private void AbonnementSeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbonnementSeniorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbonnementSeniorActionPerformed

    private void AbonnementEnfantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbonnementEnfantMouseClicked
        // TODO add your handling code here:
        this.recupAbonnement = "Enfant";
    }//GEN-LAST:event_AbonnementEnfantMouseClicked

    private void AbonnementSeniorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbonnementSeniorMouseClicked
        // TODO add your handling code here:
        this.recupAbonnement = "Senior";
    }//GEN-LAST:event_AbonnementSeniorMouseClicked

    private void AbonnementRegulierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbonnementRegulierMouseClicked
        // TODO add your handling code here:
        this.recupAbonnement = "Regulier";
    }//GEN-LAST:event_AbonnementRegulierMouseClicked
    public Boolean getConnecte() {
        return Connecte;
    }

    public String getUser() {
        return this.recupUser;
    }

    public String getMdp() {
        return this.recupMdp;
    }

    public String getMembre() {
        return this.recupAbonnement;
    }

    public String getFacture() {
        return this.recupFact;
    }

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceInscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceInscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceInscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceInscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceInscriptionClient(m_controler).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AbonnementEnfant;
    private javax.swing.JCheckBox AbonnementRegulier;
    private javax.swing.JCheckBox AbonnementSenior;
    private javax.swing.JButton EnregistrerClient;
    private javax.swing.JLabel RetourInterfaceClient;
    private javax.swing.JTextField SaisieMail;
    private javax.swing.JPasswordField SaisieMdp;
    private javax.swing.JTextField SaisieUser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
